#!/usr/bin/env bash

set -e

FQDN=`hostname`

if test -f /etc/pki/tls/certs/nginx.localhost.dhparam.pem -a; then
    exit 0
fi

openssl dhparam -out /etc/pki/tls/certs/nginx.localhost.dhparam.pem 2048
